### ISSUE TITLE
Consider implementation to allow for multiple one line `if`s

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/teddy#133]
It would be really useful to be able to specify multiple one line if. @kethinov has a particular idea in mind but the idea would something like below. Please generation ideas on what this could look like.

```html
<option (if-hasSupervisor true="selected") (if-isSupervisor true="disabled") class="supervisors" value="{supervisorId}"></option>
```

In the above example parenthesis `()` are delimiting the different one line if conditionals. @kethinov mentioned not wanting to make this to cryptic necessarily by doing above. But the above example kind of outlines the idea.

**Comment by kethinov** [comment]
After careful consideration of, uhhhh, over half a decade 😅, I've decided this feature is not feasible and won't be implemented.

The reason is to comply with the grammar of HTML. You likewise cannot query the same variable twice in the same if statement or use the same boolean logic operator twice in the same if statement due to the rules of HTML grammar requiring that no HTML attributes appear more than once on the same tag. This is now documented in the README.
