### ISSUE TITLE
Teddy should remove whitespace created when indenting/formatting Teddy tags

### ISSUE THREAD

**Issue by alallier** [rooseveltframework/teddy#357]
This can create unexpected whitespace when you do something like this for example

```html
<textarea>
  <if something>
    Some text here
  </if>
</textarea>
```

This will render a text area with 4 spaces and then the `Some text here` because it renders the spaces due to the if statement in this case.

**Comment by kethinov** [comment]
I think the solution here is to trim the beginning and end of the string with respect to the parent element.

**Comment by kethinov** [comment]
It may not be posible to fix this elegantly because it would require automatically trimming whitespace before and after the text within the `<textarea>` which could lead to lots of hacky consequences. Teddy 0.4.x did some of this and wasn't a great road to go down. Might be better to have people just do stuff like `<textarea>{content}</textarea>` where `{content}` is defined by the backend before it gets to the template.
